@startuml GridSystem

class Grid{
    - rows : int
    - columns : int
    - cellWidth : float
    - cellHeight : float
    - origin : Vector3
    - rotation : Quaternion
    - cells : Cell[,]
    - pathfindingAlgorithm : PathfindingAlgorithm
    + GridSaved : UnityEvent
    + GridLoaded : UnityEvent


    + CreateGrid(rows, columns, cellWidth, cellHeight, origin, rotation) : void
    + ResizeGrid (newRows, newColumns) : void
    + AdjustCellSize(newCellWidth, newCellHeight) : void
    + MoveGrid(newOrigin) : void
    + SaveToFile(filePath) : void
    + LoadFromFile(filePath) : void
    + FindPath(startPosition, endPosition) : List<Cell>
    + GetCell(row, column) : Cell
    + GetCell(mousePos) : Cell
    + SetCell(row, column, cell) : void
    + CombineGrids(otherGrids) : void
    + PlaceOnGrid(startingCell, gridObject) : void
    - OnDrawGizmos() : void
    - OnGridSaved() : void
    - OnGridLoaded() : void
    - IsWithinBounds(row, column) : bool
}

class Cell {
    - grid : Grid
    - row : int
    - column : int
    - state : CellState
    - occupant : IGridObject
    - groundPrefab : GameObject

    + Cell(row, column, grid) : Cell
    + GetState() : CellState
    + SetState(state) : void
    + GetOccupant() : IGridObject
    + SetOccupant(occupant) : void
    + GetCoordinnates() : Vector2Int
    + IsOccupied() : bool
    + GetNeighbors(neighborConfiguration) : List<Cell>
    + SaveCell() : void
    + LoadCell() : void
}

enum CellState {
    EMPTY
    OCCUPIED
}

enum NeighborConfiguration{
    FOUR_WAY
    EIGHT_WAY
}

interface IGridObject {
    + GetOccupiedCells(grid, startingCell) : List<Cell>
    + PlaceOnGrid(grid, startingCell) : void
    + RemoveFromGrid() : void
    + GetOccupant<T>() : T
}

interface IGridInteractable extends IGridObject {
    + OnSelected() : void
    + IsSelected() : bool
    + IsPlaced() : bool

}

class GridInteractableObject implements IGridInteractable {
    - isSelected : bool
    - isPlaced : bool
    - occupiedCells : List<Cell>
    + Selected : UnityEvent
    + PlacedGridElement : UnityEvent
    + RemovedGridElement : UnityEvent	
}

Cell --> CellState : uses
Cell --> NeighborConfiguration : uses
Grid "1" -- "0..*" Cell : contains
Cell "0..*" -- "0..1" IGridObject : occupied by

@enduml
