@startuml GridSystem

class Grid{
    - rows : int
    - columns : int
    - cellWidth : float
    - cellHeight : float
    - origin : Vector3
    - rotation : Quaternion
    - cells : Cell[,]
    - pathfindingAlgorithm : PathfindingAlgorithm
    + GridSaved : UnityEvent
    + GridLoaded : UnityEvent
    - gridId : String

    + CreateGrid(rows : int, columns : int, cellWidth : float, cellHeight : float, origin : Vector3, rotation : Quaternion) : void
    + ResizeGrid (newRows : int, newColumns : int) : void
    + AdjustCellSize(newCellWidth : float, newCellHeight : float) : void
    + MoveGrid(newOrigin : Vector3) : void
    + SaveToFile(filePath : String) : void
    + LoadFromFile(filePath : String) : void
    + FindPath(startPosition : Cell, endPosition : Cell) : List<Cell>
    + GetCell(row : int, column : int) : Cell
    + GetCellSize() : Vector2
    + GetCell(mousePos : Vector2) : Cell
    + SetCell(row : int, column : int, cell : Cell) : void
    + CombineGrids(otherGrids : List<Grid>) : void
    + GetGridID() : String
    + PlaceOnGrid(startingCell : Cell, gridObject : GameObject) : void
    + GetCellWorldPosition(row : int, column : int) : Vector3
    - IsWithinBounds(row : int, column : int) : bool
    - OnDrawGizmos() : void
    - OnGridSaved() : void
    - OnGridLoaded() : void
}

class Cell {
    - grid : Grid
    - row : int
    - column : int
    - state : CellState
    - occupant : IGridObject
    - groundPrefab : GameObject

    + Cell(row : int, column : int, grid : Grid) : Cell
    + GetState() : CellState
    + GetOccupant() : IGridObject
    + SetOccupant(occupant : IGridObject) : void
    + GetGroundPrefab() : GameObject
    + GetCoordinnates() : Vector2Int
    + AttachCellGround(groundObject : GameObject) : void
    + IsOccupied() : bool
    + GetNeighbors(neighborConfiguration : NeighborConfiguration) : List<Cell>
    + SaveCell() : void
    + LoadCell() : void
    + GetCenter() : Vector3
    + GetGridId() : String
}

class CellGround <<MonoBehaviour>> {
    - cell : Cell
    
    + OnMouseDown() : void
    + SetCellReference(cell : Cell) : void
}

enum CellState {
    EMPTY
    OCCUPIED
}

enum NeighborConfiguration{
    FOUR_WAY
    EIGHT_WAY
}

interface IGridObject {
    + GetOccupiedCells(grid : Grid, startingCell : Cell) : List<Cell>
    + PlaceOnGrid(grid : Grid, startingCell : Cell) : void
    + RemoveFromGrid() : void
    + GetOccupant<T>() : T
}

interface IGridInteractable extends IGridObject {
    + OnSelected() : void
    + IsSelected() : bool
    + IsPlaced() : bool

}

class GridInteractableObject implements IGridInteractable {
    - isSelected : bool
    - isPlaced : bool
    - occupiedCells : List<Cell>
    + Selected : UnityEvent
    + PlacedGridElement : UnityEvent
    + RemovedGridElement : UnityEvent	
}

Cell --> CellState : uses
Cell --> NeighborConfiguration : uses
Cell "1" -- "1" CellGround : has
Cell "0..*" -- "0..1" IGridObject : occupied by
Grid "1" -- "0..*" Cell : contains

@enduml
