//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/Player/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Modules"",
            ""id"": ""d1a202f8-4adb-45d2-a190-0a18f57f5da6"",
            ""actions"": [
                {
                    ""name"": ""PlaceElseGate"",
                    ""type"": ""Button"",
                    ""id"": ""dd1bb58d-3cbd-4065-8e0e-2ccaed6b4e1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlaceTurnGate"",
                    ""type"": ""Button"",
                    ""id"": ""a858d013-712a-48e1-9d53-4b9bc2b17e5c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""a052e65f-2af7-4fdb-a3c5-ddfcd01fac93"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectModule"",
                    ""type"": ""Button"",
                    ""id"": ""340f904c-489c-4876-8fdc-610aae87f74d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cb4a8d35-275e-4ccd-9e31-21265f561bda"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceElseGate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""954e97c5-23b1-44da-8746-5fb9839ee7a5"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlaceTurnGate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d41fe6d3-92b2-4aa0-9be0-22154ddeea77"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1f03af0-496e-4fad-8d1a-f8e41897cefb"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectModule"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d8abbde-8e3f-4389-85ef-f5cd8252883e"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectModule"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Modules
        m_Modules = asset.FindActionMap("Modules", throwIfNotFound: true);
        m_Modules_PlaceElseGate = m_Modules.FindAction("PlaceElseGate", throwIfNotFound: true);
        m_Modules_PlaceTurnGate = m_Modules.FindAction("PlaceTurnGate", throwIfNotFound: true);
        m_Modules_ToggleBuildMode = m_Modules.FindAction("ToggleBuildMode", throwIfNotFound: true);
        m_Modules_SelectModule = m_Modules.FindAction("SelectModule", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Modules
    private readonly InputActionMap m_Modules;
    private List<IModulesActions> m_ModulesActionsCallbackInterfaces = new List<IModulesActions>();
    private readonly InputAction m_Modules_PlaceElseGate;
    private readonly InputAction m_Modules_PlaceTurnGate;
    private readonly InputAction m_Modules_ToggleBuildMode;
    private readonly InputAction m_Modules_SelectModule;
    public struct ModulesActions
    {
        private @PlayerControls m_Wrapper;
        public ModulesActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PlaceElseGate => m_Wrapper.m_Modules_PlaceElseGate;
        public InputAction @PlaceTurnGate => m_Wrapper.m_Modules_PlaceTurnGate;
        public InputAction @ToggleBuildMode => m_Wrapper.m_Modules_ToggleBuildMode;
        public InputAction @SelectModule => m_Wrapper.m_Modules_SelectModule;
        public InputActionMap Get() { return m_Wrapper.m_Modules; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ModulesActions set) { return set.Get(); }
        public void AddCallbacks(IModulesActions instance)
        {
            if (instance == null || m_Wrapper.m_ModulesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ModulesActionsCallbackInterfaces.Add(instance);
            @PlaceElseGate.started += instance.OnPlaceElseGate;
            @PlaceElseGate.performed += instance.OnPlaceElseGate;
            @PlaceElseGate.canceled += instance.OnPlaceElseGate;
            @PlaceTurnGate.started += instance.OnPlaceTurnGate;
            @PlaceTurnGate.performed += instance.OnPlaceTurnGate;
            @PlaceTurnGate.canceled += instance.OnPlaceTurnGate;
            @ToggleBuildMode.started += instance.OnToggleBuildMode;
            @ToggleBuildMode.performed += instance.OnToggleBuildMode;
            @ToggleBuildMode.canceled += instance.OnToggleBuildMode;
            @SelectModule.started += instance.OnSelectModule;
            @SelectModule.performed += instance.OnSelectModule;
            @SelectModule.canceled += instance.OnSelectModule;
        }

        private void UnregisterCallbacks(IModulesActions instance)
        {
            @PlaceElseGate.started -= instance.OnPlaceElseGate;
            @PlaceElseGate.performed -= instance.OnPlaceElseGate;
            @PlaceElseGate.canceled -= instance.OnPlaceElseGate;
            @PlaceTurnGate.started -= instance.OnPlaceTurnGate;
            @PlaceTurnGate.performed -= instance.OnPlaceTurnGate;
            @PlaceTurnGate.canceled -= instance.OnPlaceTurnGate;
            @ToggleBuildMode.started -= instance.OnToggleBuildMode;
            @ToggleBuildMode.performed -= instance.OnToggleBuildMode;
            @ToggleBuildMode.canceled -= instance.OnToggleBuildMode;
            @SelectModule.started -= instance.OnSelectModule;
            @SelectModule.performed -= instance.OnSelectModule;
            @SelectModule.canceled -= instance.OnSelectModule;
        }

        public void RemoveCallbacks(IModulesActions instance)
        {
            if (m_Wrapper.m_ModulesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IModulesActions instance)
        {
            foreach (var item in m_Wrapper.m_ModulesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ModulesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ModulesActions @Modules => new ModulesActions(this);
    public interface IModulesActions
    {
        void OnPlaceElseGate(InputAction.CallbackContext context);
        void OnPlaceTurnGate(InputAction.CallbackContext context);
        void OnToggleBuildMode(InputAction.CallbackContext context);
        void OnSelectModule(InputAction.CallbackContext context);
    }
}
